# -*- coding: utf-8 -*-
"""Password_gen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YmpCQmtrvb_JP3wXepEQ7pyrmagTxWns
"""

import random

password_length = int(input('Passowrd length: '))

char = 'abcdefghijklmnopqrstuvwxyz0123456789'

password = ''
for i in range(password_length):
  password = password + random.choice(char)

print(password)

